apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-csharp-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-csharp-app
  template:
    metadata:
      labels:
        app: my-csharp-app
    spec:
      containers:
        - name: csharp-app-container
          image: your-csharp-image:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "256Mi"
              cpu: "0.2"
