jobs:
  create_nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    - name: Build project
      run: dotnet build --configuration Release
      working-directory: './source'

    - run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}
      working-directory: './source'

    - uses: actions/upload-artifact@v3
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: ${{ env.NuGetDirectory }}/*.nupkg
